name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: gencertify
  SERVICE_NAME: gencertify
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/235850710154/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider-new
          service_account: github-actions@gencertify.iam.gserviceaccount.com
          # Added service usage and cloud build permissions
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy to Cloud Run
        id: deploy
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --source . \
            --platform managed \
            --region ${{ env.REGION }} \
            --set-env-vars="APP_NAME=GenCertify,ENVIRONMENT=production,DEBUG=False,LOG_LEVEL=INFO,LOG_FILE=logs/app.log,API_HOST=0.0.0.0,API_PORT=8080,GOOGLE_CLOUD_PROJECT=${{ env.PROJECT_ID }},GOOGLE_CLOUD_REGION=${{ env.REGION }},FIRESTORE_COLLECTION_USERS=users,FIRESTORE_COLLECTION_CERTIFICATIONS=certifications,FIRESTORE_COLLECTION_EVALUATIONS=evaluations,FIRESTORE_COLLECTION_DOCUMENTS=documents,STORAGE_BUCKET_NAME=${{ env.PROJECT_ID }}-bucket,OPENAI_MODEL=gpt-4o,ANTHROPIC_MODEL=claude-3.7-sonnet,VERTEX_AI_LOCATION=${{ env.REGION }},VERTEX_AI_MODEL_ID=text-bison@001" \
            --set-secrets="OPENAI_API_KEY=openai-api-key:latest,ANTHROPIC_API_KEY=anthropic-api-key:latest" \
            --port=8080
            
      - name: Show URL
        run: |
          echo "Deployed to: $(gcloud run services describe ${{ env.SERVICE_NAME }} --region ${{ env.REGION }} --format='value(status.url)')"